### ISSUE TITLE
特殊类型条目+Meta模板 导出OB后不兼容问题

### ISSUE THREAD

**Issue by Zijinn** [Darkluna999/IFPM-OB-Pub#2]
**描述Bug**
NBER文章在dataview中显示的是自身标题
**截图**
![image](https://user-images.githubusercontent.com/97291951/184497918-02f13998-dcb3-46c7-9243-6c7dca8634a5.png)

可能是zotero的原因，看看大佬有没有好的解决办法。
NBER网址：https://www.nber.org/
**发生环境**
 - 系统: 
 - IF版本: 
 - OB版本: 
 - DV版本: 
 - 其他相关插件版本:

**Comment by Darkluna999** [comment]
这个方便的话可以把出错这个md文件发给我吗，我觉得大概是数据源的问题？
我试着复现了一下，这个网址抓到的文献并没有对应的刊名，在表格里也不会显示，或许是你输入了刊名？


![Image](https://user-images.githubusercontent.com/53258301/184500780-8db20ff0-43b4-44b9-80db-dab7aa54afba.png)


或者你可以处理敏感信息后把用户笔记区以上的部分发给我，发到这里也可以

**Comment by Zijinn** [comment]
当然可以，我将通过邮件发送给你

**Comment by Zijinn** [comment]
***@***.***
***@***.***


以上为源文鉴，meta笔记内容以及zotero的信息标签页。谢谢！
发件人: ***@***.***>
发送时间: 2022年8月13日 22:21
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Darkluna999/IFPM-OB-Pub] working paper的期刊问题（NBER文章） (Issue #2)


这个方便的话可以把出错这个md文件发给我吗，我觉得大概是数据源的问题？

―

**Comment by Darkluna999** [comment]
啊这，我没收到来着？

**Comment by Zijinn** [comment]
我将发送在这里。
[2021_Concentration and Resilience in the U.pdf](https://github.com/Darkluna999/IFPM-OB-Pub/files/9333423/2021_Concentration.and.Resilience.in.the.U.pdf)
![image](https://user-images.githubusercontent.com/97291951/184538953-47eca5e0-eca3-41da-9697-bb6818733c35.png)
![image](https://user-images.githubusercontent.com/97291951/184538963-7744545a-de97-4df8-9a24-e4cf8b79cd22.png)
以上为源文件，meta笔记内容以及zotero的信息标签页。谢谢！

**Comment by Darkluna999** [comment]
明白了，你抓取的条目类型是预印本，有不少键值不支持
可以去问 @qnscholar  有没有相关类型条目的支持计划，或者修复目前Meta模板的空键值生成link问题
或者当前使用yaml的模板而非Meta也可以规避这个问题(目前我的方案是这个)

**Comment by Zijinn** [comment]
好的，非常感谢！
还有一个小小的问题，即使我在已生成的md文件上补全期刊名也无法被抓取是有错误吗？还是说我键入错误？

**Comment by Darkluna999** [comment]
不要在md文件做修改，zotero里类型改为期刊然后补全数据即可

**Comment by Zijinn** [comment]
收到，非常感谢大佬！
