### ISSUE TITLE
文献星标和zotero自带快捷键冲突

### ISSUE THREAD

**Issue by Zijinn** [Darkluna999/IFPM-OB-Pub#6]
文献星标的快捷键为alt+1234，此快捷键如果在阅读模式下将会导致与zotero自带快捷键重复
冲突快捷键为以下区域：
![](https://picgobedd.oss-cn-hangzhou.aliyuncs.com/img/202208292146107.png)

**Comment by Darkluna999** [comment]
这个也不是笔记范围。。你得问猫哥
